#!/usr/bin/env bash

SNAPRM=$(sudo timeshift --list|egrep  '^0'|cut -d\  -f7)
SNAPONE=

# Gerando Snapshot
  sudo timeshift --delete --snapshot $SNAPRM
	# Deletando o Snapshot mais antigo
          sudo timeshift --create &&\
